language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules
before_install:
  - npm install hexo-cli -g
install:
  - npm install
script:
  - git clone -b master https://github.com/jerryc127/hexo-theme-butterfly.git themes/Butterfly
  - cp -rf source/img/* themes/Butterfly/source/img/
  - hexo clean
  - hexo g
after_success:
  - git clone "https://${GH_TOKEN}@${GH_REF}"
  - cp -rf public/* yolkpie.github.io/
  - cd ./yolkpie.github.io
  - git config --global user.name "${U_NAME}"
  - git config --global user.email "${U_EMAIL}"
  - git add .
  - git commit -m 'travis-ci auto build yolk-blog'
  - git push origin "${P_BRANCH}"
branches:
  only:
    - master