name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install Node.js, NPM and Yarn
      uses: actions/setup-node@v1
      with:
          node-version: 12.18.3
    - name: Install Dependencies
      run: |
            git config --global user.name yolkpie2020
            git config --global user.email yolkpie2020@163.com
            git config --global user.password 1234wbzd
            git config --list



