name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install Node.js, NPM and Yarn
      uses: actions/setup-node@v1
      with:
          node-version: 12.18.3
    - name: Install Dependencies
      run: |
            git config --global user.name "${{secrets.U_NAME}}"
            git config --global user.email "${{secrets.U_EMAIL}}"
            git config --global user.password "${{secrets.U_PASSWORD}}"
            echo git config --list



