name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Push Build
    - run: ssh-keygen -t rsa -b 4096 -C $USER_EMAIL -f ~/.ssh/id_rsa -N ''

