name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install Node.js, NPM and Yarn
      uses: actions/setup-node@v1
      with:
          node-version: 12.18.3
    - name: Install Dependencies
      run: |
            npm i
    - name: Electron Build
      run: |
            npm install hexo-cli -g
            hexo g

    - name: Push Build
      run: |
            git remote rm origin
            git remote add origin https://github.com/YolkPie/yolkpie.github.io.git
            git config --global user.name yolkpie2020
            git config --global user.email yolkpie2020@163.com
            git clone "https://oauth2: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@github.com/YolkPie/yolkpie.github.io.git"
            git config --list
            Copy-Item "public\*" "yolkpie.github.io\" -Recurse -Force
            cd ./yolkpie.github.io
            git add .
            git commit -m 'travis-ci auto build yolk-blog'
            git push origin master
            



