name: build-blog CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.18.3]

    steps:
      - run: |
           npm -v
           npm install hexo-cli -g
           npm install
           hexo g
