name: build-blog CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.18.3]

    steps:
      - run: |
             cd /
             ls -al
             npm install hexo-cli -g
             npm install
             hexo g
             git config --global user.name "${{secrets.U_NAME}}"
             git config --global user.email "${{secrets.U_EMAIL}}"
             git clone "https://${GH_TOKEN}@${{secrets.GH_REF}}"
             cp -rf public/* yolkpie.github.io/
             cd ./yolkpie.github.io
             git add .
             git commit -m 'travis-ci auto build yolk-blog'
             git push origin "${{secrets.P_BRANCH}}"
